name: GitHub Branch Protection Setup

on:
  workflow_dispatch:

jobs:
  protect-main:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
      GH_REPO: ${{ github.repository }}

    steps:
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Set branch protection for main
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GH_REPO/branches/main/protection" \
            -F required_status_checks.strict=true \
            -F required_status_checks.contexts[]=check-freeze \
            -F required_status_checks.contexts[]=build \
            -F enforce_admins=true \
            -F required_pull_request_reviews.dismiss_stale_reviews=true \
            -F required_pull_request_reviews.required_approving_review_count=1 \
            -F restrictions=null

  protect-develop:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
      GH_REPO: ${{ github.repository }}

    steps:
      - name: Set branch protection for develop
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GH_REPO/branches/develop/protection" \
            -F required_status_checks.strict=true \
            -F required_status_checks.contexts[]=build \
            -F enforce_admins=true \
            -F required_pull_request_reviews.dismiss_stale_reviews=true \
            -F required_pull_request_reviews.required_approving_review_count=1 \
            -F restrictions=null

  protect-release-hotfix:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
      GH_REPO: ${{ github.repository }}

    steps:
      - name: Set branch protection for release/* and hotfix/*
        run: |
          echo "⚠️ GitHub API does not support wildcard protection on branches via REST."
          echo "Apply protection manually or automate it per actual branch name (e.g., release/v1.0.0)"
